name: pre-commit

steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: 3.11
- name: Install Poetry
  uses: snok/install-poetry@v1
- name: Install dependencies
  run: |
    poetry install
- name: Run pre-commit
  run: |
    pre-commit run --all-files
